
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.KeyStroke;
import javax.swing.text.Keymap;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mano
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    public Home() {
        initComponents();
    }
    String token = "";
    String number = "0";
    KeyListener listener = new KeyListener() 
    {
 
        @Override

        public void keyPressed(KeyEvent event) {

            int code = event.getKeyCode();
            System.out.println("   Code: " + KeyEvent.getKeyText(code));
            switch(KeyEvent.getKeyText(code))
            {
                case "0":
                    btnZero.doClick();
                    break;
                case "NumPad-0":
                    btnZero.doClick();
                    break;
                case "1":
                    btnOne.doClick();
                    break;
                case "NumPad-1":
                    btnOne.doClick();
                    break;
                case"2":
                    btnTwo.doClick();
                    break;
                case "NumPad-2":
                    btnTwo.doClick();
                    break;
                case"3":
                    btnThree.doClick();
                    break;
                case "NumPad-3":
                    btnThree.doClick();
                    break;
                case"4":
                    btnFour.doClick();
                    break;
                case "NumPad-4":
                    btnFour.doClick();
                    break;
                case"5":
                    btnFive.doClick();
                    break;
                case "NumPad-5":
                    btnFive.doClick();
                    break;
                case"6":
                    btnSix.doClick();
                    break;
                case "NumPad-6":
                    btnSix.doClick();
                    break;
                case"7":
                    btnSeven.doClick();
                    break;  
                case "NumPad-7":
                    btnSeven.doClick();
                    break;
                case"8":
                    btnEight.doClick();
                    break;
                case "NumPad-8":
                    btnEight.doClick();
                    break;
                case"9":
                    btnNine.doClick();
                    break;
                case "NumPad-9":
                    btnNine.doClick();
                    break;
                case"NumPad +":
                    btnSum.doClick();
                    break;
                case"NumPad -":
                    btnDifference.doClick();
                    break;
                case"Minus":
                    btnDifference.doClick();
                    break;
                case"NumPad *":
                    btnMultiplication.doClick();
                    break;
                case"NumPad /":
                    btnDivison.doClick();
                    break;
                case"Equals":
                    btnEqual.doClick();
                    break;
                case"Enter":
                    btnEqual.doClick();
                    break;
                case"Backspace":
                    btnDelete.doClick();
                    break;
                case"NumPad .":
                    btnDot.doClick();
                    break;
                case"Period":
                    btnDot.doClick();
                    break;
            }
        }
        @Override

        public void keyReleased(KeyEvent event)
        {

        }
        @Override

        public void keyTyped(KeyEvent event)
        {

        }
    };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnZero = new javax.swing.JButton();
        btnZero.setMnemonic(KeyEvent.VK_Y);
        btnDot = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnOne = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDivison = new javax.swing.JButton();
        btnSum = new javax.swing.JButton();
        btnDifference = new javax.swing.JButton();
        btnMultiplication = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnPower = new javax.swing.JButton();
        btnFactorial = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(240, 42, 130));

        jTextField1.addKeyListener(listener);
        jTextField1.setBackground(new java.awt.Color(240, 42, 130));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField1.setForeground(java.awt.Color.white);
        jTextField1.setText("0");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTextField1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextField1.getAccessibleContext().setAccessibleName("");
        jTextField1.getAccessibleContext().setAccessibleDescription("");
        jTextField1.setEditable(false);

        jPanel4.setBackground(new java.awt.Color(53, 53, 53));
        jPanel4.setForeground(new java.awt.Color(53, 53, 53));

        btnZero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnZero.setForeground(java.awt.Color.white);
        btnZero.setText("0");
        btnZero.setAlignmentX(10.0F);
        btnZero.setBorder(null);
        btnZero.setContentAreaFilled(false);
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });
        btnZero.addKeyListener(listener);

        btnDot.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDot.setForeground(java.awt.Color.white);
        btnDot.setText(".");
        btnDot.setBorderPainted(false);
        btnDot.setContentAreaFilled(false);
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });
        btnDot.addKeyListener(listener);

        btnEqual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnEqual.setForeground(new java.awt.Color(240, 42, 130));
        btnEqual.setText("=");
        btnEqual.setBorderPainted(false);
        btnEqual.setContentAreaFilled(false);
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });
        btnEqual.addKeyListener(listener);

        btnOne.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnOne.setForeground(java.awt.Color.white);
        btnOne.setText("1");
        btnOne.setBorderPainted(false);
        btnOne.setContentAreaFilled(false);
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        btnFour.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnFour.setForeground(java.awt.Color.white);
        btnFour.setText("4");
        btnFour.setBorderPainted(false);
        btnFour.setContentAreaFilled(false);
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });
        btnFour.addKeyListener(listener);

        btnTwo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnTwo.setForeground(java.awt.Color.white);
        btnTwo.setText("2");
        btnTwo.setBorderPainted(false);
        btnTwo.setContentAreaFilled(false);
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });
        btnTwo.addKeyListener(listener);

        btnThree.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnThree.setForeground(java.awt.Color.white);
        btnThree.setText("3");
        btnThree.setBorderPainted(false);
        btnThree.setContentAreaFilled(false);
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });
        btnThree.addKeyListener(listener);

        btnFive.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnFive.setForeground(java.awt.Color.white);
        btnFive.setText("5");
        btnFive.setBorderPainted(false);
        btnFive.setContentAreaFilled(false);
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });
        btnFive.addKeyListener(listener);

        btnSix.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSix.setForeground(java.awt.Color.white);
        btnSix.setText("6");
        btnSix.setBorderPainted(false);
        btnSix.setContentAreaFilled(false);
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });
        btnSix.addKeyListener(listener);

        btnSeven.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSeven.setForeground(java.awt.Color.white);
        btnSeven.setText("7");
        btnSeven.setBorderPainted(false);
        btnSeven.setContentAreaFilled(false);
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });
        btnSeven.addKeyListener(listener);

        btnEight.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnEight.setForeground(java.awt.Color.white);
        btnEight.setText("8");
        btnEight.setBorderPainted(false);
        btnEight.setContentAreaFilled(false);
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });
        btnEight.addKeyListener(listener);

        btnNine.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnNine.setForeground(java.awt.Color.white);
        btnNine.setText("9");
        btnNine.setBorderPainted(false);
        btnNine.setContentAreaFilled(false);
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });
        btnNine.addKeyListener(listener);

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDelete.setForeground(java.awt.Color.white);
        btnDelete.setText("Del");
        btnDelete.setToolTipText("");
        btnDelete.setBorderPainted(false);
        btnDelete.setContentAreaFilled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        btnDelete.addKeyListener(listener);

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnClear.setForeground(java.awt.Color.white);
        btnClear.setText("CL");
        btnClear.setBorderPainted(false);
        btnClear.setContentAreaFilled(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        btnClear.addKeyListener(listener);

        btnDivison.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDivison.setForeground(new java.awt.Color(240, 42, 130));
        btnDivison.setText("÷");
        btnDivison.setBorderPainted(false);
        btnDivison.setContentAreaFilled(false);
        btnDivison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisonActionPerformed(evt);
            }
        });
        btnDivison.addKeyListener(listener);

        btnSum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSum.setForeground(new java.awt.Color(240, 42, 130));
        btnSum.setText("+");
        btnSum.setBorderPainted(false);
        btnSum.setContentAreaFilled(false);
        btnSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumActionPerformed(evt);
            }
        });
        btnSum.addKeyListener(listener);

        btnDifference.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDifference.setForeground(new java.awt.Color(240, 42, 130));
        btnDifference.setText("-");
        btnDifference.setBorderPainted(false);
        btnDifference.setContentAreaFilled(false);
        btnDifference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDifferenceActionPerformed(evt);
            }
        });
        btnDifference.addKeyListener(listener);

        btnMultiplication.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMultiplication.setForeground(new java.awt.Color(240, 42, 130));
        btnMultiplication.setText("X");
        btnMultiplication.setBorderPainted(false);
        btnMultiplication.setContentAreaFilled(false);
        btnMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicationActionPerformed(evt);
            }
        });
        btnMultiplication.addKeyListener(listener);

        btnTan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnTan.setForeground(java.awt.Color.white);
        btnTan.setText("Tan");
        btnTan.setBorderPainted(false);
        btnTan.setContentAreaFilled(false);
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });
        btnTan.addKeyListener(listener);

        btnPower.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnPower.setForeground(java.awt.Color.white);
        btnPower.setText("Pow");
        btnPower.setBorder(null);
        btnPower.setBorderPainted(false);
        btnPower.setContentAreaFilled(false);
        btnPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerActionPerformed(evt);
            }
        });
        btnPower.addKeyListener(listener);

        btnFactorial.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnFactorial.setForeground(new java.awt.Color(240, 42, 130));
        btnFactorial.setText("!");
        btnFactorial.setBorder(null);
        btnFactorial.setBorderPainted(false);
        btnFactorial.setContentAreaFilled(false);
        btnFactorial.addKeyListener(listener);
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 42, 130));
        jButton1.setText("Taylor Swift");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(240, 42, 130));
        jButton2.setText("-/+");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9))
                            .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSix, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThree, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPower, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnDifference, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                        .addComponent(btnSum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnEqual, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(btnTan)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnDelete)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDivison))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(35, 35, 35)
                                    .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDivison, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete)
                            .addComponent(btnTan)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMultiplication, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDifference, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPower, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        btnOne.addKeyListener(listener);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.addKeyListener(listener);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void calculate(String operation)
    {
        String currentValue = jTextField1.getText();
        CalculatorControler controler = CalculatorControler.getInstance();
        int indexOfOperator = 0;
        if(token.compareTo("") == 0)
        {
            if(operation.compareTo("(") == 0)
            {
                token = "(";
                return;
            }
            else if (operation.compareTo("!") == 0)
            {
                token = "!";
                changeFontAndsetTextFeild(currentValue + "!");
                return;
            }
            number = currentValue;
            token = operation;
            changeFontAndsetTextFeild(currentValue + operation);
        }
        else
        {
            String secondValue = "";
            switch(token)
            {
                case "+":
                    indexOfOperator = currentValue.lastIndexOf("+");
                    for(int i =indexOfOperator+1;i<currentValue.length();i++)
                    {
                        secondValue+= currentValue.charAt(i);
                    }
                    if(indexOfOperator == currentValue.length()-1 )
                    {
                        token = operation;
                        changeFontAndsetTextFeild(currentValue.substring(0, currentValue.length()-1) + operation);
                    }
                    else
                    {
                        number = "" + controler.addition(Float.parseFloat(number), Float.parseFloat(secondValue));
                        changeFontAndsetTextFeild(number + operation);
                        token = operation;
                    }
                    break;
                case "-":
                    indexOfOperator = currentValue.lastIndexOf("-");
                    for(int i =indexOfOperator+1;i<currentValue.length();i++)
                    {
                        secondValue+= currentValue.charAt(i);
                    }
                    if(indexOfOperator == currentValue.length()-1 )
                    {
                        token = operation;
                        changeFontAndsetTextFeild(currentValue.substring(0, currentValue.length()-1) + operation);
                    }
                    else
                    {
                        number = "" + controler.subtraction(Float.parseFloat(number), Float.parseFloat(secondValue));
                        changeFontAndsetTextFeild(number + operation);
                        token = operation;
                    }
                    break;
                case "X":
                    indexOfOperator = currentValue.lastIndexOf("X");
                    for(int i =indexOfOperator+1;i<currentValue.length();i++)
                    {
                        secondValue+= currentValue.charAt(i);
                    }
                    if(indexOfOperator == currentValue.length()-1 )
                    {
                        token = operation;
                        changeFontAndsetTextFeild(currentValue.substring(0, currentValue.length()-1) + operation);
                    }
                    else
                    {
                        number = "" + controler.multiplication(Float.parseFloat(number), Float.parseFloat(secondValue));
                        changeFontAndsetTextFeild(number + operation);
                        token = operation;
                    }
                    break;
                case "÷":
                    indexOfOperator = currentValue.lastIndexOf("÷");
                    for(int i =indexOfOperator+1;i<currentValue.length();i++)
                    {
                        secondValue+= currentValue.charAt(i);
                    }
                    if(Float.parseFloat(secondValue) == 0)
                    {
                        btnClear.doClick();
                        return;
                    }
                    if(indexOfOperator == currentValue.length()-1 )
                    {
                        token = operation;
                        changeFontAndsetTextFeild(currentValue.substring(0, currentValue.length()-1) + operation);
                    }
                    else
                    {
                        number = "" + controler.division(Float.parseFloat(number), Float.parseFloat(secondValue));
                        changeFontAndsetTextFeild(number + operation);
                        token = operation;
                    }
                    break;
                case "^":
                    indexOfOperator = currentValue.lastIndexOf("^");
                    for(int i =indexOfOperator+1;i<currentValue.length();i++)
                    {
                        secondValue+= currentValue.charAt(i);
                    }
                    if(indexOfOperator == currentValue.length()-1 )
                    {
                        token = operation;
                        changeFontAndsetTextFeild(currentValue.substring(0, currentValue.length()-1) + operation);
                    }
                    else
                    {
                        number = "" + controler.power(Float.parseFloat(number), Float.parseFloat(secondValue));
                        changeFontAndsetTextFeild(number + operation);
                        token = operation;
                    }
                    break;
                case "(":
                    indexOfOperator = currentValue.lastIndexOf("(");
                    for(int i =indexOfOperator+1;i<currentValue.length();i++)
                    {
                        secondValue+= currentValue.charAt(i);
                    }
                    if(Float.parseFloat(secondValue) == 90)
                    {
                        btnClear.doClick();
                        return;
                        
                    }
                    if(indexOfOperator == currentValue.length()-1 )
                    {
                        token = operation;
                        changeFontAndsetTextFeild(currentValue.substring(0, currentValue.length()-1) + operation);
                    }
                    else
                    {
                        number = "" + controler.tan(Float.parseFloat(secondValue));
                        if(operation.compareTo("(") == 0)
                        {
                            changeFontAndsetTextFeild("tan(" + number);
                            token = "(";
                        }
                        else
                        {
                            changeFontAndsetTextFeild(number + operation);
                            token = operation;
                        }
                        
                        
                    }
                    break;
                case "!":
                    indexOfOperator = currentValue.lastIndexOf("!");
                    for(int i =0;i<indexOfOperator;i++)
                    {
                        secondValue+= currentValue.charAt(i);
                    }
                    number = "" + controler.factorial(Float.parseFloat(secondValue));
                    changeFontAndsetTextFeild(number + operation);
                    token = operation;
            }
        }
    }
    private int numberOfChar(String s, char c)
    {
        int count = 0;
        for(int i =0;i<s.length();i++)
        {
            if(s.charAt(i) == c)
                count++;
        }
        return count;
    }
    private void changeFontAndsetTextFeild(String value)
    {
        if(value.length() >15 && (jTextField1.getFont().getSize() > 15)  )
        {
            Font font1 = new Font("Tahoma", Font.PLAIN, 40 - value.length());
            jTextField1.setFont(font1);
        }
        jTextField1.setText(value);
    }
    private void btnMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicationActionPerformed
        calculate("X");
    }//GEN-LAST:event_btnMultiplicationActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("0");
        token = "";
        number = "";
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDivisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisonActionPerformed
        calculate("÷");
    }//GEN-LAST:event_btnDivisonActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        // TODO add your handling code here:
        String currentValue = jTextField1.getText();
        if(currentValue.compareTo("0") == 0)
        {
            jTextField1.setText("4");
        }
        else
        {
          changeFontAndsetTextFeild(currentValue + "4");
        }
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        // TODO add your handling code here:
        String currentValue = jTextField1.getText();
        if(currentValue.compareTo("0") == 0)
        {
            jTextField1.setText("1");
        }
        else
        {
           changeFontAndsetTextFeild(currentValue + "1");
           //jTextField1.setText(currentValue + "1");
        }
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        // TODO add your handling code here:
        String currentValue = jTextField1.getText();
        int count = numberOfChar(currentValue, '.');;
        if((currentValue.contains("+") || currentValue.contains("-") || currentValue.contains("X")  || currentValue.contains("^") || currentValue.contains("÷")) && count<2)
        {
            currentValue += ".";
            changeFontAndsetTextFeild(currentValue);
        }
        else if (count<1)
        {
            currentValue += ".";
            changeFontAndsetTextFeild(currentValue);
        }
    }//GEN-LAST:event_btnDotActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        // TODO add your handling code here:
        String currentValue = jTextField1.getText();
        if(currentValue.compareTo("0") == 0)
        {
            jTextField1.setText("0");
        }
        else
        {
          jTextField1.setText(currentValue + "0");
        }
        
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        // TODO add your handling code here:
        String currentValue = jTextField1.getText();
        if(currentValue.compareTo("0") == 0)
        {
            jTextField1.setText("2");
        }
        else
        {
            changeFontAndsetTextFeild(currentValue + "2");
        }
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        // TODO add your handling code here:
        String currentValue = jTextField1.getText();
        if(currentValue.compareTo("0") == 0)
        {
            jTextField1.setText("3");
        }
        else 
        {
          changeFontAndsetTextFeild(currentValue + "3");
        }
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        // TODO add your handling code here:
        String currentValue = jTextField1.getText();
        if(currentValue.compareTo("0") == 0)
        {
            jTextField1.setText("5");
        }
        else
        {
          changeFontAndsetTextFeild(currentValue + "5");
        }
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        // TODO add your handling code here:
        String currentValue = jTextField1.getText();
        if(currentValue.compareTo("0") == 0)
        {
            jTextField1.setText("6");
        }
        else
        {
            changeFontAndsetTextFeild(currentValue + "6");
        }
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
        // TODO add your handling code here:
        String currentValue = jTextField1.getText();
        if(currentValue.compareTo("0") == 0)
        {
            jTextField1.setText("7");
        }
        else
        {
            changeFontAndsetTextFeild(currentValue + "7");
        }
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        String currentValue = jTextField1.getText();
        if(currentValue.compareTo("tan(") == 0)
        {
            return;
        }
        if(token.compareTo("") != 0 && currentValue.contains("tan(") == false)
        {
            int indexOfOperator = currentValue.lastIndexOf(token);
            if(indexOfOperator == currentValue.length()-1)
            {
                token = "(";
                jTextField1.setText("tan(" + number);
            }
            
        }
        else if(currentValue.contains("tan(") == true )
        {
            calculate("(");
        }
        else
        {
            jTextField1.setText("tan(");
            calculate("(");
        }
    }//GEN-LAST:event_btnTanActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        // TODO add your handling code here:
        String currentValue = jTextField1.getText();
        if(currentValue.contains("+"))
        {
            calculate("+");
        }
        else if(currentValue.contains("-"))
        {
            calculate("-");
        }
        else if(currentValue.contains("X"))
        {
            calculate("X");
        }
        else if(currentValue.contains("÷"))
        {
            calculate("÷");
        }
        else if(currentValue.contains("^"))
        {
            calculate("^");
        }
        else if(currentValue.contains("("))
        {
            calculate("(");
        }
        else if(currentValue.contains("!"))
        {
            calculate("!");
        }
    }//GEN-LAST:event_btnEqualActionPerformed

    private void btnSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumActionPerformed
        calculate("+");
    }//GEN-LAST:event_btnSumActionPerformed

    private void btnDifferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDifferenceActionPerformed
        calculate("-");
    }//GEN-LAST:event_btnDifferenceActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
        // TODO add your handling code here:
        String currentValue = jTextField1.getText();
        if(currentValue.compareTo("0") == 0)
        {
            jTextField1.setText("8");
        }
        else
        {
            changeFontAndsetTextFeild(currentValue + "9");
        }
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        // TODO add your handling code here:
        String currentValue = jTextField1.getText();
        if(currentValue.compareTo("0") == 0)
        {
            jTextField1.setText("9");
        }
        else
        {
          jTextField1.setText(currentValue + "9");
        }
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerActionPerformed
        calculate("^");
    }//GEN-LAST:event_btnPowerActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String currentValue = jTextField1.getText();
        if(currentValue.compareTo("0") == 0)
        {
            return;
        }
        if(currentValue.compareTo("tan(") == 0)
        {
            jTextField1.setText("0");
            token = "";
            number = "";
            return;
        }
        if(currentValue.charAt(currentValue.length()-1) == '+' || currentValue.charAt(currentValue.length()-1) == '-' || currentValue.charAt(currentValue.length()-1) == 'X'
            || currentValue.charAt(currentValue.length()-1) == '÷' || currentValue.charAt(currentValue.length()-1) == '^')
        {
            token = "";
            jTextField1.setText(currentValue.substring(0, currentValue.length()-1));
        }
        else
        {
            jTextField1.setText(currentValue.substring(0, currentValue.length()-1));
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
        calculate("!");
    }//GEN-LAST:event_btnFactorialActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Image image = new Image();
        image.setVisible(true);
        image.setResizable(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDifference;
    private javax.swing.JButton btnDivison;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnMultiplication;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnPower;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnSum;
    private javax.swing.JButton btnTan;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}

